### ISSUE TITLE
[Bug] moving in the Dvalin battle can kick you out of the dungeon

### ISSUE THREAD

**Issue by Hartie95** [Hartie95/Grasscutter#27]
If you move via W,A,S,D during the dvalin battle, the game will kick you out of the dungeon.
We need to find out why, and how to stop it from happening

**Comment by mjolsic** [comment]
In the ofiicial, you actually wont be able to move in the dvalin flight, or more accurately,  it feels like there is a box that contains the character. So you will still be able to see the character following the movement keys, but the charater will stay on the spot, rather than moving extensively. Not sure if a packet does that or what.

**Comment by Hartie95** [comment]
got fixed in one of the recent backports frmo hidden
